name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure...
        2. Run qualitarr...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (set LOG_LEVEL=debug for more details)
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your config.yaml (remove sensitive data like API keys)
      render: yaml
    validations:
      required: false

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      options:
        - Docker
        - Docker Compose
        - Manual (Node.js)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Qualitarr Version
      placeholder: "2.0.0"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false
